-- Themes
local cmd = vim.cmd
local set_hl = vim.api.nvim_set_hl
local autocmd = vim.api.nvim_create_autocmd
local utils = require('utils')

-- Lualine transparent bg
set_hl(0, 'lualine_transitional_lualine_a_replace_to_StatusLine', { bg = 'None' })
set_hl(0, 'lualine_transitional_lualine_a_insert_to_StatusLine', { bg = 'None' })
set_hl(0, 'lualine_transitional_lualine_a_normal_to_StatusLine', { bg = 'None' })
set_hl(0, 'lualine_transitional_lualine_a_command_to_StatusLine', { bg = 'None' })
set_hl(0, 'lualine_transitional_lualine_a_visual_to_StatusLine', { bg = 'None' })

-- LSP Diagnostics
cmd [[
sign define DiagnosticSignError text= texthl=DiagnosticError linehl= numhl=
sign define DiagnosticSignWarn  text= texthl=DiagnosticWarn  linehl= numhl=
sign define DiagnosticSignInfo  text= texthl=DiagnosticInfo  linehl= numhl=
sign define DiagnosticSignHint  text= texthl=DiagnosticHint  linehl= numhl=
]]
set_hl(0, 'DiagnosticError', { fg = 'red', bg = 'None' })
set_hl(0, 'DiagnosticWarn', { fg = 'orange', bg = 'None' })
set_hl(0, 'DiagnosticInfo', { fg = 'teal', bg = 'None' })
set_hl(0, 'DiagnosticHint', { fg = 'white', bg = 'None' })

-- Bufferline Transparency
set_hl(0, 'BufferLineNumbersSelected', { bg = 'None', fg = 'white' })
set_hl(0, 'BufferLineBufferSelected', { fg = white, bg = 'None' })
set_hl(0, 'BufferLineDiagnosticSelected', { bg = 'None' })
set_hl(0, 'BufferLineHintSelected', { bg = 'None' })
set_hl(0, 'BufferLineHintDiagnosticSelected', { bg = 'None' })
set_hl(0, 'BufferLineInfoSelected', { bg = 'None' })
set_hl(0, 'BufferLineInfoDiagnosticSelected', { bg = 'None' })
set_hl(0, 'BufferLineWarningSelected', { bg = 'None' })
set_hl(0, 'BufferLineWarningDiagnosticSelected', { bg = 'None' })
set_hl(0, 'BufferLineErrorSelected', { bg = 'None' })
set_hl(0, 'BufferLineErrorDiagnosticSelected', { bg = 'None' })
set_hl(0, 'BufferLineModifiedSelected', { bg = 'None' })
set_hl(0, 'BufferLineModifiedDiagnosticSelected', { bg = 'None' })
set_hl(0, 'BufferLineDuplicateSelected', { bg = 'None' })
set_hl(0, 'BufferLineSeparatorSelected', { fg = 'None', bg = 'None' })

-- Extra HTML syntax highlighting
set_hl(0, 'htmlArg', { italic = true })
set_hl(0, 'htmlBold', { bold = true })
set_hl(0, 'htmlItalic', { italic = true })
set_hl(0, 'htmlBoldItalic', { bold = true, italic = true })

-- Additional Transparency
set_hl(0, 'Normal', { bg = 'None', ctermbg = 'None' })
set_hl(0, 'SignColumn', { bg = 'None' })
set_hl(0, 'Pmenu', { bg = 'None', ctermbg = 'None' })
set_hl(0, 'NonText', { fg = 'gray', bg = 'None' })
set_hl(0, 'NormalFloat', { bg = 'None', ctermbg = 'None' })

local theme = {
  -- grays
	["gray-10"] =  '#aaaaaa',
	["gray-15"] =  '#a3a3a3',
	["gray-25"] =  '#999999',
	["gray-55"] =  '#555555',
	["gray-80"] =  '#3a3a3a',
	["gray-85"] =  '#333333',
	["gray-95"] =  '#222222',
  ["gray-100"] = '#111111',
  -- greens
  ["green-25"] = '#B8BB26',
  -- yellows
  ["yellow-25"] = '#FABD2F',
  -- oranges
  ["orange-25"] = '#FE8019',
  -- reds
  ["red-25"] = '#FB4934',
  -- purples
  ["purple-25"] = '#D3869B',
  -- blues
  ["blue-25"] = '#83A598',
  -- aquas
  ["aqua-25"] = '#8EC07C',
}

if os.getenv("THEME_VARIANT") == 'light' then
  for i, color in pairs(theme) do
    theme[i] = utils.invert_hex_color(color)
  end
end

-- Git signs column plugin
set_hl(0, 'MarkviewCode', { bg = theme['gray-100'] })
set_hl(0, 'MarkviewCodeInfo', { fg = theme['gray-55'], bg = theme['gray-100'] })
set_hl(0, 'MarkviewInlineCode', { fg = theme['orange-25'], bg = theme['gray-95'] })
set_hl(0, 'MarkviewHeading1', { fg = '#000000', bg = theme['green-25'] })
set_hl(0, 'MarkviewHeading2', { fg = '#000000', bg = theme['yellow-25'] })
set_hl(0, 'MarkviewHeading3', { fg = '#000000', bg = theme['orange-25'] })
set_hl(0, 'MarkviewHeading4', { fg = '#000000', bg = theme['red-25'] })
set_hl(0, 'MarkviewHeading5', { fg = '#000000', bg = theme['purple-25'] })
set_hl(0, 'MarkviewHeading6', { fg = '#000000', bg = theme['blue-25'] })

-- Italic comments
set_hl(0, 'Comment', { bg = 'None', fg = theme['gray-55'], italic = true })

-- Spelling
set_hl(0, 'SpellBad', { undercurl = true })
set_hl(0, 'SpellRare', { undercurl = true })
set_hl(0, 'SpellCap', { undercurl = true })
set_hl(0, 'SpellLocal', { undercurl = true })

-- Tab Icons
set_hl(0, 'DevIconDiffCurrent', { bg = 'None', fg = '#41535b' })
set_hl(0, 'DevIconElmCurrent', { bg = 'None', fg = '#519aba' })
set_hl(0, 'DevIconJlCurrent', { bg = 'None', fg = '#a270ba' })
set_hl(0, 'DevIconDockerfileCurrent', { bg = 'None', fg = '#458ee6' })
set_hl(0, 'DevIconXcPlaygroundCurrent', { bg = 'None', fg = '#e37933' })
set_hl(0, 'DevIconSlnCurrent', { bg = 'None', fg = '#854cc7' })
set_hl(0, 'DevIconTclCurrent', { bg = 'None', fg = '#1e5cb3' })
set_hl(0, 'DevIconFsxCurrent', { bg = 'None', fg = '#519aba' })
set_hl(0, 'DevIconTexCurrent', { bg = 'None', fg = '#3d6117' })
set_hl(0, 'DevIconLuaCurrent', { bg = 'None', fg = '#51a0cf' })
set_hl(0, 'DevIconJsxCurrent', { bg = 'None', fg = '#20c2e3' })
set_hl(0, 'DevIconWasmCurrent', { bg = 'None', fg = '#5c4cdb' })
set_hl(0, 'DevIconValaCurrent', { bg = 'None', fg = '#7239b3' })
set_hl(0, 'DevIconGemfileCurrent', { bg = 'None', fg = '#701516' })
set_hl(0, 'DevIconNPMrcCurrent', { bg = 'None', fg = '#e8274b' })
set_hl(0, 'DevIconPlCurrent', { bg = 'None', fg = '#519aba' })
set_hl(0, 'DevIconMlCurrent', { bg = 'None', fg = '#e37933' })
set_hl(0, 'DevIconMarkdownCurrent', { bg = 'None', fg = '#519aba' })
set_hl(0, 'DevIconCpCurrent', { bg = 'None', fg = '#519aba' })
set_hl(0, 'DevIconLogCurrent', { bg = 'None', fg = '#ffffff' })
set_hl(0, 'DevIconPycCurrent', { bg = 'None', fg = '#ffe291' })
set_hl(0, 'DevIconCppCurrent', { bg = 'None', fg = '#519aba' })
set_hl(0, 'DevIconEppCurrent', { bg = 'None', fg = '#ffa61a' })
set_hl(0, 'DevIconGitConfigCurrent', { bg = 'None', fg = '#41535b' })
set_hl(0, 'DevIconDesktopEntryCurrent', { bg = 'None', fg = '#563d7c' })
set_hl(0, 'DevIconClojureCurrent', { bg = 'None', fg = '#8dc149' })
set_hl(0, 'DevIconLiquidCurrent', { bg = 'None', fg = '#95bf47' })
set_hl(0, 'DevIconHppCurrent', { bg = 'None', fg = '#a074c4' })
set_hl(0, 'DevIconKotlinScriptCurrent', { bg = 'None', fg = '#7f52ff' })
set_hl(0, 'DevIconBrewfileCurrent', { bg = 'None', fg = '#701516' })
set_hl(0, 'DevIconExCurrent', { bg = 'None', fg = '#a074c4' })
set_hl(0, 'DevIconMliCurrent', { bg = 'None', fg = '#e37933' })
set_hl(0, 'DevIconEexCurrent', { bg = 'None', fg = '#a074c4' })
set_hl(0, 'DevIconGitModulesCurrent', { bg = 'None', fg = '#41535b' })
set_hl(0, 'DevIconEdnCurrent', { bg = 'None', fg = '#519aba' })
set_hl(0, 'DevIconGodotProjectCurrent', { bg = 'None', fg = '#6d8086' })
set_hl(0, 'DevIconSvgCurrent', { bg = 'None', fg = '#ffb13b' })
set_hl(0, 'DevIconXulCurrent', { bg = 'None', fg = '#e37933' })
set_hl(0, 'DevIconDartCurrent', { bg = 'None', fg = '#03589c' })
set_hl(0, 'DevIconCMakeCurrent', { bg = 'None', fg = '#6d8086' })
set_hl(0, 'DevIconOrgModeCurrent', { bg = 'None', fg = '#77aa99' })
set_hl(0, 'DevIconTextSceneCurrent', { bg = 'None', fg = '#a074c4' })
set_hl(0, 'DevIconHxxCurrent', { bg = 'None', fg = '#a074c4' })
set_hl(0, 'DevIconBazelCurrent', { bg = 'None', fg = '#89e051' })
set_hl(0, 'DevIconCobolCurrent', { bg = 'None', fg = '#005ca5' })
set_hl(0, 'DevIconCxxCurrent', { bg = 'None', fg = '#519aba' })
set_hl(0, 'DevIconGitLogoCurrent', { bg = 'None', fg = '#f14c28' })
set_hl(0, 'DevIconJpegCurrent', { bg = 'None', fg = '#a074c4' })
set_hl(0, 'DevIconWebpackCurrent', { bg = 'None', fg = '#519aba' })
set_hl(0, 'DevIconTomlCurrent', { bg = 'None', fg = '#6d8086' })
set_hl(0, 'DevIconDocCurrent', { bg = 'None', fg = '#185abd' })
set_hl(0, 'DevIconLessCurrent', { bg = 'None', fg = '#563d7c' })
set_hl(0, 'DevIconPptCurrent', { bg = 'None', fg = '#cb4a32' })
set_hl(0, 'DevIconBmpCurrent', { bg = 'None', fg = '#a074c4' })
set_hl(0, 'DevIconSqlCurrent', { bg = 'None', fg = '#dad8d8' })
set_hl(0, 'DevIconGitCommitCurrent', { bg = 'None', fg = '#41535b' })
set_hl(0, 'DevIconPrismaCurrent', { bg = 'None', fg = '#ffffff' })
set_hl(0, 'DevIconRlibCurrent', { bg = 'None', fg = '#dea584' })
set_hl(0, 'DevIconBzlCurrent', { bg = 'None', fg = '#89e051' })
set_hl(0, 'DevIconEnvCurrent', { bg = 'None', fg = '#faf743' })
set_hl(0, 'DevIconFsharpCurrent', { bg = 'None', fg = '#519aba' })
set_hl(0, 'DevIconReScriptInterfaceCurrent', { bg = 'None', fg = '#f55385' })
set_hl(0, 'DevIconLicenseCurrent', { bg = 'None', fg = '#cbcb41' })
set_hl(0, 'DevIconYmlCurrent', { bg = 'None', fg = '#6d8086' })
set_hl(0, 'DevIconXmlCurrent', { bg = 'None', fg = '#e37933' })
set_hl(0, 'DevIconGvimrcCurrent', { bg = 'None', fg = '#019833' })
set_hl(0, 'DevIconTwigCurrent', { bg = 'None', fg = '#8dc149' })
set_hl(0, 'DevIconMjsCurrent', { bg = 'None', fg = '#f1e05a' })
set_hl(0, 'DevIconSmlCurrent', { bg = 'None', fg = '#e37933' })
set_hl(0, 'DevIconCjsCurrent', { bg = 'None', fg = '#cbcb41' })
set_hl(0, 'DevIconHeexCurrent', { bg = 'None', fg = '#a074c4' })
set_hl(0, 'DevIconCsonCurrent', { bg = 'None', fg = '#cbcb41' })
set_hl(0, 'DevIconDsStoreCurrent', { bg = 'None', fg = '#41535b' })
set_hl(0, 'DevIconVagrantfileCurrent', { bg = 'None', fg = '#1563ff' })
set_hl(0, 'DevIconMixLockCurrent', { bg = 'None', fg = '#a074c4' })
set_hl(0, 'DevIconDropboxCurrent', { bg = 'None', fg = '#0061fe' })
set_hl(0, 'DevIconCMakeListsCurrent', { bg = 'None', fg = '#6d8086' })
set_hl(0, 'DevIconExsCurrent', { bg = 'None', fg = '#a074c4' })
set_hl(0, 'DevIconBinaryGLTFCurrent', { bg = 'None', fg = '#ffb13b' })
set_hl(0, 'DevIconTypeScriptReactSpecCurrent', { bg = 'None', fg = '#1354bf' })
set_hl(0, 'DevIconDumpCurrent', { bg = 'None', fg = '#dad8d8' })
set_hl(0, 'DevIconZshprofileCurrent', { bg = 'None', fg = '#89e051' })
set_hl(0, 'DevIconPsbCurrent', { bg = 'None', fg = '#519aba' })
set_hl(0, 'DevIconTextResourceCurrent', { bg = 'None', fg = '#cbcb41' })
set_hl(0, 'DevIconSuoCurrent', { bg = 'None', fg = '#854cc7' })
set_hl(0, 'DevIconNimCurrent', { bg = 'None', fg = '#f3d400' })
set_hl(0, 'DevIconWebmanifestCurrent', { bg = 'None', fg = '#f1e05a' })
set_hl(0, 'DevIconPackageLockJsonCurrent', { bg = 'None', fg = '#7a0d21' })
set_hl(0, 'DevIconEslintrcCurrent', { bg = 'None', fg = '#4b32c3' })
set_hl(0, 'DevIconLeexCurrent', { bg = 'None', fg = '#a074c4' })
set_hl(0, 'DevIconMintCurrent', { bg = 'None', fg = '#87c095' })
set_hl(0, 'DevIconTestJsCurrent', { bg = 'None', fg = '#cbcb41' })
set_hl(0, 'DevIconWebpCurrent', { bg = 'None', fg = '#a074c4' })
set_hl(0, 'DevIconVHDLCurrent', { bg = 'None', fg = '#019833' })
set_hl(0, 'DevIconSystemVerilogCurrent', { bg = 'None', fg = '#019833' })
set_hl(0, 'DevIconPsdCurrent', { bg = 'None', fg = '#519aba' })
set_hl(0, 'DevIconBabelrcCurrent', { bg = 'None', fg = '#cbcb41' })
set_hl(0, 'DevIconHrlCurrent', { bg = 'None', fg = '#b83998' })
set_hl(0, 'DevIconRbCurrent', { bg = 'None', fg = '#701516' })
set_hl(0, 'DevIconGitlabCICurrent', { bg = 'None', fg = '#e24329' })
set_hl(0, 'DevIconMakefileCurrent', { bg = 'None', fg = '#6d8086' })
set_hl(0, 'DevIconBashProfileCurrent', { bg = 'None', fg = '#89e051' })
set_hl(0, 'DevIconGitAttributesCurrent', { bg = 'None', fg = '#41535b' })
set_hl(0, 'DevIconClojureCCurrent', { bg = 'None', fg = '#8dc149' })
set_hl(0, 'DevIconTerraformCurrent', { bg = 'None', fg = '#5f43e9' })
set_hl(0, 'DevIconPrologCurrent', { bg = 'None', fg = '#e4b854' })
set_hl(0, 'DevIconFennelCurrent', { bg = 'None', fg = '#fff3d7' })
set_hl(0, 'DevIconJson5Current', { bg = 'None', fg = '#cbcb41' })
set_hl(0, 'DevIconTxtCurrent', { bg = 'None', fg = '#89e051' })
set_hl(0, 'DevIconRCurrent', { bg = 'None', fg = '#358a5b' })
set_hl(0, 'DevIconZshrcCurrent', { bg = 'None', fg = '#89e051' })
set_hl(0, 'DevIconDocxCurrent', { bg = 'None', fg = '#185abd' })
set_hl(0, 'DevIconJsonCurrent', { bg = 'None', fg = '#cbcb41' })
set_hl(0, 'DevIconGifCurrent', { bg = 'None', fg = '#a074c4' })
set_hl(0, 'DevIconRmdCurrent', { bg = 'None', fg = '#519aba' })
set_hl(0, 'DevIconXlsxCurrent', { bg = 'None', fg = '#207245' })
set_hl(0, 'DevIconZshCurrent', { bg = 'None', fg = '#89e051' })
set_hl(0, 'DevIconVerilogCurrent', { bg = 'None', fg = '#019833' })
set_hl(0, 'DevIconCrystalCurrent', { bg = 'None', fg = '#c8c8c8' })
set_hl(0, 'DevIconJpgCurrent', { bg = 'None', fg = '#a074c4' })
set_hl(0, 'DevIconSpecJsCurrent', { bg = 'None', fg = '#cbcb41' })
set_hl(0, 'DevIconBazelBuildCurrent', { bg = 'None', fg = '#89e051' })
set_hl(0, 'DevIconJavaScriptReactTestCurrent', { bg = 'None', fg = '#20c2e3' })
set_hl(0, 'DevIconFsscriptCurrent', { bg = 'None', fg = '#519aba' })
set_hl(0, 'DevIconSigCurrent', { bg = 'None', fg = '#e37933' })
set_hl(0, 'DevIconZigCurrent', { bg = 'None', fg = '#f69a1b' })
set_hl(0, 'DevIconSvelteCurrent', { bg = 'None', fg = '#ff3e00' })
set_hl(0, 'DevIconCCurrent', { bg = 'None', fg = '#599eff' })
set_hl(0, 'DevIconEjsCurrent', { bg = 'None', fg = '#cbcb41' })
set_hl(0, 'DevIconGruntfileCurrent', { bg = 'None', fg = '#e37933' })
set_hl(0, 'DevIconZshenvCurrent', { bg = 'None', fg = '#89e051' })
set_hl(0, 'DevIconBazelWorkspaceCurrent', { bg = 'None', fg = '#89e051' })
set_hl(0, 'DevIconCPlusPlusCurrent', { bg = 'None', fg = '#f34b7d' })
set_hl(0, 'DevIconSettingsJsonCurrent', { bg = 'None', fg = '#854cc7' })
set_hl(0, 'DevIconImportConfigurationCurrent', { bg = 'None', fg = '#ececec' })
set_hl(0, 'DevIconVimrcCurrent', { bg = 'None', fg = '#019833' })
set_hl(0, 'DevIconHtmlCurrent', { bg = 'None', fg = '#e44d26' })
set_hl(0, 'DevIconSwiftCurrent', { bg = 'None', fg = '#e37933' })
set_hl(0, 'DevIconClojureDartCurrent', { bg = 'None', fg = '#519aba' })
set_hl(0, 'DevIconStylCurrent', { bg = 'None', fg = '#8dc149' })
set_hl(0, 'DevIconLhsCurrent', { bg = 'None', fg = '#a074c4' })
set_hl(0, 'DevIconScalaCurrent', { bg = 'None', fg = '#cc3e44' })
set_hl(0, 'DevIconTerminalCurrent', { bg = 'None', fg = '#31b53e' })
set_hl(0, 'DevIconGulpfileCurrent', { bg = 'None', fg = '#cc3e44' })
set_hl(0, 'DevIconCoffeeCurrent', { bg = 'None', fg = '#cbcb41' })
set_hl(0, 'DevIconSolidityCurrent', { bg = 'None', fg = '#519aba' })
set_hl(0, 'DevIconPsScriptModulefileCurrent', { bg = 'None', fg = '#6975c4' })
set_hl(0, 'DevIconHamlCurrent', { bg = 'None', fg = '#eaeae1' })
set_hl(0, 'DevIconNPMIgnoreCurrent', { bg = 'None', fg = '#e8274b' })
set_hl(0, 'DevIconXlsCurrent', { bg = 'None', fg = '#207245' })
set_hl(0, 'DevIconAwkCurrent', { bg = 'None', fg = '#4d5a5e' })
set_hl(0, 'DevIconGoCurrent', { bg = 'None', fg = '#519aba' })
set_hl(0, 'DevIconScssCurrent', { bg = 'None', fg = '#f55385' })
set_hl(0, 'DevIconTFVarsCurrent', { bg = 'None', fg = '#5f43e9' })
set_hl(0, 'DevIconRsCurrent', { bg = 'None', fg = '#dea584' })
set_hl(0, 'DevIconPhpCurrent', { bg = 'None', fg = '#a074c4' })
set_hl(0, 'DevIconHtmCurrent', { bg = 'None', fg = '#e34c26' })
set_hl(0, 'DevIconTsCurrent', { bg = 'None', fg = '#519aba' })
set_hl(0, 'DevIconPngCurrent', { bg = 'None', fg = '#a074c4' })
set_hl(0, 'DevIconMotokoCurrent', { bg = 'None', fg = '#9772fb' })
set_hl(0, 'DevIconReScriptCurrent', { bg = 'None', fg = '#cc3e44' })
set_hl(0, 'DevIconDefaultCurrent', { bg = 'None', fg = '#6d8086' })
set_hl(0, 'DevIconsbtCurrent', { bg = 'None', fg = '#cc3e44' })
set_hl(0, 'DevIconProcfileCurrent', { bg = 'None', fg = '#a074c4' })
set_hl(0, 'DevIconRssCurrent', { bg = 'None', fg = '#fb9d3b' })
set_hl(0, 'DevIconCsCurrent', { bg = 'None', fg = '#596706' })
set_hl(0, 'DevIconFsCurrent', { bg = 'None', fg = '#519aba' })
set_hl(0, 'DevIconKotlinCurrent', { bg = 'None', fg = '#7f52ff' })
set_hl(0, 'DevIconBatCurrent', { bg = 'None', fg = '#c1f12e' })
set_hl(0, 'DevIconHbsCurrent', { bg = 'None', fg = '#f0772b' })
set_hl(0, 'DevIconJsCurrent', { bg = 'None', fg = '#cbcb41' })
set_hl(0, 'DevIconMdxCurrent', { bg = 'None', fg = '#519aba' })
set_hl(0, 'DevIconHsCurrent', { bg = 'None', fg = '#a074c4' })
set_hl(0, 'DevIconKshCurrent', { bg = 'None', fg = '#4d5a5e' })
set_hl(0, 'DevIconGraphQLCurrent', { bg = 'None', fg = '#e535ab' })
set_hl(0, 'DevIconBashrcCurrent', { bg = 'None', fg = '#89e051' })
set_hl(0, 'DevIconOPUSCurrent', { bg = 'None', fg = '#f88a02' })
set_hl(0, 'DevIconCshCurrent', { bg = 'None', fg = '#4d5a5e' })
set_hl(0, 'DevIconCssCurrent', { bg = 'None', fg = '#42a5f5' })
set_hl(0, 'DevIconFortranCurrent', { bg = 'None', fg = '#734f96' })
set_hl(0, 'DevIconConfigurationCurrent', { bg = 'None', fg = '#ececec' })
set_hl(0, 'DevIconGemspecCurrent', { bg = 'None', fg = '#701516' })
set_hl(0, 'DevIconPmCurrent', { bg = 'None', fg = '#519aba' })
set_hl(0, 'DevIconConfigRuCurrent', { bg = 'None', fg = '#701516' })
set_hl(0, 'DevIconTestTsCurrent', { bg = 'None', fg = '#519aba' })
set_hl(0, 'DevIconPackageJsonCurrent', { bg = 'None', fg = '#e8274b' })
set_hl(0, 'DevIconErlCurrent', { bg = 'None', fg = '#b83998' })
set_hl(0, 'DevIconDroolsCurrent', { bg = 'None', fg = '#ffafaf' })
set_hl(0, 'DevIconQueryCurrent', { bg = 'None', fg = '#90a850' })
set_hl(0, 'DevIconSchemeCurrent', { bg = 'None', fg = '#000000' })
set_hl(0, 'DevIconDbCurrent', { bg = 'None', fg = '#dad8d8' })
set_hl(0, 'DevIconPyCurrent', { bg = 'None', fg = '#ffbc03' })
set_hl(0, 'DevIconMaterialCurrent', { bg = 'None', fg = '#b83998' })
set_hl(0, 'DevIconIniCurrent', { bg = 'None', fg = '#6d8086' })
set_hl(0, 'DevIconDCurrent', { bg = 'None', fg = '#427819' })
set_hl(0, 'DevIconOpenTypeFontCurrent', { bg = 'None', fg = '#ececec' })
set_hl(0, 'DevIconRakeCurrent', { bg = 'None', fg = '#701516' })
set_hl(0, 'DevIconLockCurrent', { bg = 'None', fg = '#bbbbbb' })
set_hl(0, 'DevIconClojureJSCurrent', { bg = 'None', fg = '#519aba' })
set_hl(0, 'DevIconBashCurrent', { bg = 'None', fg = '#89e051' })
set_hl(0, 'DevIconIcoCurrent', { bg = 'None', fg = '#cbcb41' })
set_hl(0, 'DevIconAiCurrent', { bg = 'None', fg = '#cbcb41' })
set_hl(0, 'DevIconRprojCurrent', { bg = 'None', fg = '#358a5b' })
set_hl(0, 'DevIconVueCurrent', { bg = 'None', fg = '#8dc149' })
set_hl(0, 'DevIconGDScriptCurrent', { bg = 'None', fg = '#6d8086' })
set_hl(0, 'DevIconGitIgnoreCurrent', { bg = 'None', fg = '#41535b' })
set_hl(0, 'DevIconJavaCurrent', { bg = 'None', fg = '#cc3e44' })
set_hl(0, 'DevIconFaviconCurrent', { bg = 'None', fg = '#cbcb41' })
set_hl(0, 'DevIconHCurrent', { bg = 'None', fg = '#a074c4' })
set_hl(0, 'DevIconPdfCurrent', { bg = 'None', fg = '#b30b00' })
set_hl(0, 'DevIconPydCurrent', { bg = 'None', fg = '#ffe291' })
set_hl(0, 'DevIconNodeModulesCurrent', { bg = 'None', fg = '#e8274b' })
set_hl(0, 'DevIconSassCurrent', { bg = 'None', fg = '#f55385' })
set_hl(0, 'DevIconNixCurrent', { bg = 'None', fg = '#7ebae4' })
set_hl(0, 'DevIconLuauCurrent', { bg = 'None', fg = '#51a0cf' })
set_hl(0, 'DevIconYamlCurrent', { bg = 'None', fg = '#6d8086' })
set_hl(0, 'DevIconPsScriptfileCurrent', { bg = 'None', fg = '#4273ca' })
set_hl(0, 'DevIconSpecTsCurrent', { bg = 'None', fg = '#519aba' })
set_hl(0, 'DevIconHhCurrent', { bg = 'None', fg = '#a074c4' })
set_hl(0, 'DevIconCsvCurrent', { bg = 'None', fg = '#89e051' })
set_hl(0, 'DevIconPyoCurrent', { bg = 'None', fg = '#ffe291' })
set_hl(0, 'DevIconVimCurrent', { bg = 'None', fg = '#019833' })
set_hl(0, 'DevIconMdCurrent', { bg = 'None', fg = '#ffffff' })
set_hl(0, 'DevIconPsManifestfileCurrent', { bg = 'None', fg = '#6975c4' })
set_hl(0, 'DevIconSlimCurrent', { bg = 'None', fg = '#e34c26' })
set_hl(0, 'DevIconFishCurrent', { bg = 'None', fg = '#4d5a5e' })
set_hl(0, 'DevIconJavaScriptReactSpecCurrent', { bg = 'None', fg = '#20c2e3' })
set_hl(0, 'DevIconMustacheCurrent', { bg = 'None', fg = '#e37933' })
set_hl(0, 'DevIconFsiCurrent', { bg = 'None', fg = '#519aba' })
set_hl(0, 'DevIconTorCurrent', { bg = 'None', fg = '#519aba' })
set_hl(0, 'DevIconRakefileCurrent', { bg = 'None', fg = '#701516' })
set_hl(0, 'DevIconTypeScriptReactTestCurrent', { bg = 'None', fg = '#1354bf' })
set_hl(0, 'DevIconPackedResourceCurrent', { bg = 'None', fg = '#6d8086' })
set_hl(0, 'DevIconErbCurrent', { bg = 'None', fg = '#701516' })
set_hl(0, 'DevIconShCurrent', { bg = 'None', fg = '#4d5a5e' })
set_hl(0, 'DevIconConfCurrent', { bg = 'None', fg = '#6d8086' })
set_hl(0, 'DevIconPpCurrent', { bg = 'None', fg = '#ffa61a' })
set_hl(0, 'DevIconTsxCurrent', { bg = 'None', fg = '#1354bf' })

-- Invisiblish pane separators
set_hl(0, 'VertSplit', { bg = 'None', fg = theme['gray-95'] })

-- Floating borders
set_hl(0, 'PmenuBorder', { fg = theme['gray-85'], ctermfg = 'gray', bg = 'None', ctermbg = 'None' })
set_hl(0, 'FloatBorder', { fg = theme['gray-85'], ctermfg = 'gray', bg = 'None', ctermbg = 'None' })

-- LspInfo
set_hl(0, 'LspInfoBorder', { fg = theme['gray-95'], ctermfg = 'gray', bg = 'None', ctermbg = 'None' })

-- Git signs column plugin
set_hl(0, 'GitSignsAdd', { fg = 'SpringGreen2', bg = 'None' })
set_hl(0, 'GitSignsAddLn', { fg = 'SpringGreen2', bg = 'None' })
set_hl(0, 'GitSignsAddNr', { fg = 'SpringGreen2', bg = 'None' })
set_hl(0, 'GitSignsChange', { fg = 'MediumPurple2', bg = 'None' })
set_hl(0, 'GitSignsChangeLn', { fg = 'MediumPurple2', bg = 'None' })
set_hl(0, 'GitSignsChangeNr', { fg = 'MediumPurple2', bg = 'None' })
set_hl(0, 'GitSignsChangeDelete', { fg = 'Orange1', bg = 'None' })
set_hl(0, 'GitSignsChangeDeleteLn', { fg = 'Orange1', bg = 'None' })
set_hl(0, 'GitSignsChangeDeleteNr', { fg = 'Orange1', bg = 'None' })
set_hl(0, 'GitSignsUntracked', { fg = 'SkyBlue1', bg = 'None' })
set_hl(0, 'GitSignsUntrackedLn', { fg = 'SkyBlue1', bg = 'None' })
set_hl(0, 'GitSignsUntrackedNr', { fg = 'SkyBlue1', bg = 'None' })
set_hl(0, 'GitSignsTopDelete', { fg = 'Red1', bg = 'None' })
set_hl(0, 'GitSignsTopDeleteLn', { fg = 'Red1', bg = 'None' })
set_hl(0, 'GitSignsTopDeleteNr', { fg = 'Red1', bg = 'None' })
set_hl(0, 'GitSignsDelete', { fg = 'Red1', bg = 'None' })
set_hl(0, 'GitSignsDeleteLn', { fg = 'Red1', bg = 'None' })
set_hl(0, 'GitSignsDeleteNr', { fg = 'Red1', bg = 'None' })

-- Cursorline
set_hl(0, 'CursorLine', { bg = theme['gray-95'] })
set_hl(0, 'CursorLineNr', { bg = theme['gray-95'], fg = theme['orange-25'] }) -- Also highlight number column

-- Folds
set_hl(0, 'Folded', { bg =  'None', fg = theme['gray-85'], bold = false, nocombine = true })

-- Highlight current row in NORMAL mode,
-- hide highlight in INSERT mode
autocmd({ 'InsertEnter', 'InsertLeave' }, { pattern = '*', command = 'set cul!' })
